version: "3"
services:
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=jzzs2020"
      - "MYSQL_DATABASE=jzzs"
      - "TZ=Asia/Shanghai"
    ports:
      - 33066:3306
